[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'lib/snekmate/src']
solc = "0.8.23"
evm_version = "cancun"
skip = ["**/lib/snekmate/**"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
]

[fmt]
single_line_statement_blocks = "single"
multiline_func_header = "params_first"
sort_imports = true
contract_new_lines = true
line_length = 150
number_underscore = "preserve"
quote_style = "double"
ignore = ["lib/", "src/lender/Lender.sol"]

[invariant]
runs = 50
depth = 50

# See more config options https://github.com/foundry-rs/foundry/tree/master/config